ls
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Cache::Delete
sudo su
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exir
exit
./otobo.Console.log Maint::L~og::Clear
./otobo.Console.log Maint::Log::Clear
./otobo.Console.log
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.COnsole.pl Maint::Cache::Delete
ls
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
ls
./otobo.Config.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
cd 
cd /opt/otobo/bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
cd /opt/otobo/bin
./otobo.Console.pl Maint::Cache::Delete
exit
cd bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
cd /opt/otobo/bin
ls
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Config::Rebuild
exit
cd bin
./otobo.Console.pl Maint::Cache::Delete
exit
cd bin
./otobo.Console.pl Maint::Cache::Delete
exit
cd bin
./otobo.Console.pl Maint::Config::Rebuild
cd 
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl
./otobo.Console.pl  Maint::Log::Clear 
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
cd otobo
cd bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl  Maint::Log::Clear 
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl  Maint::Log::Clear 
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl  Maint::Log::Clear 
./otobo.Console.pl Maint::Cache::Delete
cd /opt/otobo/bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Config::Rebuild
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
cd bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
cd /opt/otobo/bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
cd /opt/otobo/bin
ls
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Config::Rebuild
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Config::Rebuild
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Config::Rebuild
exit
exit
./otobo.Console.pl Maint::Cache::Delete
cd bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Config::Rebuild
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Config::Rebuild
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Log::Clear
cd bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
exit
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
exit
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
cd /opt/otobo/bin
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
exit
cd /opt/otobo/bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
cd bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
cd bin
./otobo.Console.pl Maint::Log::Clear
cd bin
./otobo.Console.pl Maint::Log::Clear
cd bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Cache::Delete
./otobo.Console.pl Maint::Log::Clear
exit
cd bin
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
./otobo.Console.pl Maint::Log::Clear
