"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketAction=(function(TargetNS){function SerializeData(Data){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});return QueryString;}
function OpenCustomerUserAddressBook(RecipientField,RecipientFieldLabel,RecipientType){var CustomerUserAddressBookIFrameURL,CustomerUserAddressBookIFrame;CustomerUserAddressBookIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AgentCustomerUserAddressBook;RecipientField='+RecipientField+';RecipientFieldLabel='+RecipientFieldLabel+';RecipientType='+RecipientType;CustomerUserAddressBookIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerUserAddressBookIFrame='<iframe class="TextOption CustomerUserAddressBook" src="'+CustomerUserAddressBookIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerUserAddressBookIFrame,'','10px','Center',true);}
function OpenCustomerDialog(){var CustomerIFrameURL,CustomerIFrame;CustomerIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AdminCustomerUser;Nav=None;Subject=;What=';CustomerIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerIFrame='<iframe class="TextOption Customer" src="'+CustomerIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerIFrame,'','10px','Center',true);}
function OpenCustomerIDSelection(){var Data={Action:'AgentCustomerSearch',Subaction:'AssignedCustomerIDs',CustomerUserID:$('#SelectedCustomerUser').val(),};$('#SelectionCustomerIDAssigned').empty();Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){$.each(Response,function(Index,CustomerID){var CustomerIDOption=new Option(CustomerID,CustomerID);CustomerIDOption.innerHTML=CustomerID;$('#SelectionCustomerIDAssigned').append(CustomerIDOption);});if(!$('#SelectionCustomerIDAssigned > option').length){$('#TemplateSelectionCustomerID fieldset:last').addClass('Hidden');}
else{$('#TemplateSelectionCustomerID fieldset:last').removeClass('Hidden');}
Core.UI.Dialog.ShowContentDialog($('#TemplateSelectionCustomerID'),Core.Language.Translate('Select a customer ID to assign to this ticket'),'10px','Center',true);Core.Agent.CustomerSearch.InitSimple($('#SelectionCustomerIDAll'));$('#SelectionCustomerIDAssigned').val($('#CustomerID').val()).trigger('redraw.InputField').trigger('change');$('#SelectionCustomerIDAll').on('select.Autocomplete',function(){CloseCustomerIDSelection($(this).val());});$('#SelectionCustomerIDAssigned').on('change',function(){CloseCustomerIDSelection($(this).val());});});}
function CloseCustomerIDSelection(CustomerID){$('#CustomerID').val(CustomerID);$('#ShowCustomerID').html(CustomerID);Core.UI.Dialog.CloseDialog($('.Dialog'));}
function MarkPrimaryCustomer(){$('.CustomerContainer').children('div').each(function(){var $InputObj=$(this).find('.CustomerTicketText'),$RadioObj=$(this).find('.CustomerTicketRadio');if($RadioObj.prop('checked')){$InputObj.addClass('MainCustomer');}
else{$InputObj.removeClass('MainCustomer');}});}
TargetNS.Init=function(){$('.OptionCustomerUserAddressBook').on('click',function(){OpenCustomerUserAddressBook($(this).data('recipient-field'),$(this).data('recipient-field-label'),$(this).data('recipient-type'));return false;});$('#OptionCustomer').on('click',function(){OpenCustomerDialog();return false;});$('#SelectionCustomerID').on('click',function(){OpenCustomerIDSelection();return false;});Core.UI.InputFields.Deactivate($('#TemplateSelectionCustomerID'));MarkPrimaryCustomer();Core.App.Subscribe('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',function(){MarkPrimaryCustomer();});$('#submitRichText').on('click',function(Event){var ToCustomer=$('#ToCustomer').val()||'',CcCustomer=$('#CcCustomer').val()||'',BccCustomer=$('#BccCustomer').val()||'',FromCustomer=$('#FromCustomer').val()||'';if(ToCustomer.length||CcCustomer.length||BccCustomer.length||FromCustomer.length){window.setTimeout(function(){$('#submitRichText').trigger('click');},100);Event.preventDefault();Event.stopPropagation();return false;}});Core.App.Subscribe('Event.UI.ToggleWidget',function($WidgetElement){if($WidgetElement.attr('id')!=='WidgetArticle'){return;}
if($WidgetElement.hasClass('Expanded')){$('#CreateArticle').prop('checked',true);}});};TargetNS.UpdateCustomer=function(Customer){var $UpdateForm=$('form[name=compose]',parent.document);$UpdateForm
.find('#ExpandCustomerName').val('2')
.end()
.find('#PreSelectedCustomerUser').val(Customer)
.end()
.submit();parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));};TargetNS.SelectRadioButton=function(Value,Name){$('input[type="radio"][name='+Name+'][value='+Value+']').prop('checked',true);};TargetNS.ConfirmTemplateOverwrite=function(FieldName,$TemplateSelect,Callback){var Content='',LastValue=$TemplateSelect.data('LastValue')||'';Content=$('#'+FieldName).val();if(typeof CKEDITOR!=='undefined'&&CKEDITOR.instances[FieldName]){Content=CKEDITOR.instances[FieldName].getData();}
if(Content.length&&!window.confirm(Core.Language.Translate('Setting a template will overwrite any text or attachment.')+' '+Core.Language.Translate('Do you really want to continue?')))
{$TemplateSelect.val(LastValue).trigger('redraw');}
else if($.isFunction(Callback)){Callback();$TemplateSelect.data('LastValue',$TemplateSelect.val());}}
Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.TicketAction||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.Admin=Core.Agent.Admin||{};Core.Agent.Admin.CustomerUser=(function(TargetNS){TargetNS.Init=function(){var Customer=Core.Config.Get('Customer');var Nav=Core.Config.Get('Nav');$('.CustomerAutoCompleteSimple').each(function(){Core.Agent.CustomerSearch.InitSimple($(this));});if(!Nav||Nav!='None'){return;}
if(Customer){Core.Agent.TicketAction.UpdateCustomer(Core.Language.Translate(Customer));}
$('#CustomerTable a').click(function(){Core.Agent.TicketAction.UpdateCustomer($(this).text());});};Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.Admin.CustomerUser||{}));

