// The content of this file is automatically generated, do not edit.
Core.Language.Load({"Completeness":null,"DateFormat":"%M/%D/%Y %T","DateFormatLong":"%T - %M/%D/%Y","DateFormatShort":"%M/%D/%Y","DateInputFormat":"%M/%D/%Y","DateInputFormatLong":"%M/%D/%Y - %T","DecimalSeparator":".","LanguageCode":"en","Separator":","}, {"May_long":"May"});
